sequenceDiagram
    participant A as Adapter
    participant D as DSP
    participant dAPI as DepAPI

    Note over A,dAPI: Deposit Initialization
    A->>D: deposit_init()
    D->>dAPI: POST depositions/new
    dAPI-->>D: deposition id
    D-->>A: deposition id

    loop For each file
        Note over A,dAPI: File Validation
        A->>D: validate_file(fd) | validate() (all)
        D-->>A: is valid?

        Note over A,dAPI: File Upload
        A->>D: add_file(fd, ft)
    
        D->>dAPI: POST depositions/{dep_id}/files/
        dAPI-->>D: file id
        D-->>A: file id
    end

    Note over A,dAPI: Deposit Processing
    A->>D: deposit()
    D->>dAPI: POST depositions/{dep_id}/process
    dAPI-->>D: processing status
    D-->>A: processing status
    Note right of dAPI: This does NOT return a pdb/emdb id yet.<br/>This is just to process files.<br/>To get a pdb/emdb id, the user needs to:<br/>1. Log in to DepUI<br/>2. Fill out the rest of metadata<br/>3. Download validation report<br/>4. Check ligands, sequence, assembly<br/>5. Submit